### Numpy Exercises

#### No. 1

In [2]:
import numpy as np

#### No. 2

In [16]:
# Print the numpy version and the configuration
np.__version__
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/FAISAL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/FAISAL/anacon

#### No. 3

In [17]:
arr_1 = np.zeros(10)
arr_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

No. 4

In [18]:
arr_1.size
arr_1.nbytes

80

No. 5

In [27]:
# How to get the documentation of the numpy add function from the command line?
!pydoc numpy.add

Help on ufunc in numpy:

numpy.add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the

No. 6

In [21]:
arr2 = np.zeros(10)
arr2[4] = 1
print(arr_2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


No. 7

In [20]:
arr3 = np.arange(10, 50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

No. 8

In [24]:
# Reverse a vector
arr3 = arr3[::-1]
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

No. 9

In [25]:
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


No. 10

In [26]:
# 9. Find indices of non-zero elements from [1,2,0,0,4,0]
arr4 = np.nonzero([1,2,0,0,4,0])
arr4

(array([0, 1, 4], dtype=int64),)

No. 11

In [30]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

No. 12

In [31]:
# Create a 3x3x3 array with random values
arr5 = np.random.rand(3, 3, 3)
print(arr5)

[[[0.49829534 0.2692849  0.05720427]
  [0.21619655 0.77646548 0.84308117]
  [0.72725601 0.40934673 0.49214325]]

 [[0.9811063  0.78111182 0.32594145]
  [0.94597473 0.59491437 0.47675025]
  [0.93232742 0.83663207 0.31789959]]

 [[0.57359173 0.74682388 0.83593027]
  [0.07621484 0.25321446 0.85903113]
  [0.33635035 0.92618428 0.91914722]]]


No. 13

In [36]:
# Create a 10x10 array with random values and find the minimum and maximum values
arr6 = np.random.rand(10, 10)
print(arr6)
print("Minimum:", np.min(arr6))
print("Maximum:", np.max(arr6))

[[0.14016264 0.81540237 0.3084884  0.81419493 0.62582366 0.04660105
  0.49433614 0.34046253 0.12643892 0.36525771]
 [0.18009972 0.37398292 0.09929006 0.22440077 0.09718816 0.72028914
  0.86776104 0.73282805 0.57004597 0.08686318]
 [0.7679932  0.07872325 0.75296554 0.57861164 0.80447399 0.31652543
  0.02788051 0.77190545 0.66893666 0.50350574]
 [0.100158   0.74606612 0.90495915 0.39131846 0.2077369  0.29216955
  0.72100543 0.11483802 0.22970533 0.63484218]
 [0.40111679 0.72765709 0.7499722  0.3333706  0.9071306  0.88890257
  0.00574626 0.29915303 0.40687263 0.26476554]
 [0.70083576 0.89835641 0.14860146 0.70039205 0.17103222 0.10776395
  0.84839007 0.33592229 0.72669695 0.22688397]
 [0.60853308 0.31250088 0.40858528 0.86214642 0.18512632 0.5623952
  0.76905105 0.7764991  0.75772145 0.28517831]
 [0.45741718 0.30170751 0.13710082 0.7777656  0.50460206 0.30951424
  0.98008877 0.88112673 0.50854923 0.67565352]
 [0.85150568 0.04701197 0.06828903 0.64533457 0.69913069 0.3176109
  0.34303896 0

No. 14

In [43]:
# Create a random vector of size 30 and find the mean value
arr7 = np.random.rand(30)
print("Mean:", np.mean(arr7))

Mean: 0.47903042231484666


No. 15

In [42]:
# Create a 2d array with 1 on the border and 0 inside
arr8 = np.ones((4, 4))
arr8[1:-1, 1:-1] = 0
print(arr8)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


No. 16

In [44]:
# Define an existing array
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Get the shape of the existing array
rows, cols = existing_array.shape

# Create a new array with increased dimensions (adding 2 to both rows and columns for the border)
new_rows = rows + 2
new_cols = cols + 2

# Create a new array filled with zeros with the increased dimensions
new_array = np.zeros((new_rows, new_cols), dtype=existing_array.dtype)

# Copy the existing array into the center of the new array
new_array[1:-1, 1:-1] = existing_array

print("Existing array:")
print(existing_array)

print("\nArray with border of zeros:")
print(new_array)

Existing array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with border of zeros:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


No. 17

In [45]:
# 0 * np.nan
result1 = 0 * np.nan

# np.nan == np.nan
result2 = np.nan == np.nan

# np.inf > np.nan
result3 = np.inf > np.nan

# np.nan - np.nan
result4 = np.nan - np.nan

# np.nan in set([np.nan])
result5 = np.nan in set([np.nan])

# 0.3 == 3 * 0.1
result6 = 0.3 == 3 * 0.1

print("Result 1:", result1)
print("Result 2:", result2)
print("Result 3:", result3)
print("Result 4:", result4)
print("Result 5:", result5)
print("Result 6:", result6)

Result 1: nan
Result 2: False
Result 3: False
Result 4: nan
Result 5: True
Result 6: False


No. 18

In [48]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix_5x5 = np.diag(1 + np.arange(4), k=-1)
print(matrix_5x5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


No. 19

In [50]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
arr_8x8 = np.zeros((8, 8), dtype=int)
arr_8x8[1::2, ::2] = 1
arr_8x8[::2, 1::2] = 1
print(arr_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


No. 20

In [54]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr10 = (6, 7, 8)
index_100 = np.unravel_index(100, arr10)
print("Index of the 100th element:", index_100)

Index of the 100th element: (1, 5, 4)


No. 21

In [56]:
# Create a checkerboard 8x8 matrix using the tile function
checkerboard_tile = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


No. 22

In [61]:
# Normalize a 5x5 random matrix
random_matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (random_matrix_5x5 - np.mean(random_matrix_5x5)) / np.std(random_matrix_5x5)
print(normalized_matrix)

[[ 1.15644809 -0.72776062  1.50126707  0.44792556 -0.68044575]
 [ 0.14060052  1.68271063 -0.64263086 -0.02979589  1.04864051]
 [-1.24180579 -0.94716129 -0.65471693 -0.77100398  0.30389194]
 [-0.93516396 -0.86630862  1.77549922 -1.1359365   0.29382427]
 [-0.45385015  0.98035722 -1.25401862  1.70739724 -0.69796332]]


No. 23

In [62]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_dtype = np.dtype([('R', np.ubyte),
                        ('G', np.ubyte),
                        ('B', np.ubyte),
                        ('A', np.ubyte)])
print("\nCustom dtype for RGBA color:", color_dtype)


Custom dtype for RGBA color: [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


No. 24

In [64]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix_5x3 = np.random.randint(0, 10, (5, 3))
matrix_3x2 = np.random.randint(0, 10, (3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print("\nProduct of 5x3 and 3x2 matrices:")
print(product_matrix)


Product of 5x3 and 3x2 matrices:
[[38 34]
 [77 63]
 [11 13]
 [53 59]
 [73 47]]


No. 25

In [65]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
array_1d = np.arange(11)
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1
print("\nNegated elements between 3 and 8:")
print(array_1d)


Negated elements between 3 and 8:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
